### PR TITLE
Pushing back to latest maven with vulnerability fixes - will require java 7

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@harawata Tossing this your way as ~18 months ago I had went to 3.3.3 and you reverted for a release.  I'm not sure if that still matters or not.  If it does, I'll cancel and back out for only necessary bits.  In addition to maven upgrade (I've been doing a lot lately), I patched most of their underlying dependencies as they are either significantly out of date for no reason or vulnerable.

**Comment by harawata** [comment]
Hi @hazendaz ,

I would like to release one more version that is compatible with Java 6 and am waiting for the core 3.4.6 release.

**Comment by hazendaz** [comment]
@harawata sure.  no problem.  I thought that might end up being the case.  I'll let this sit around and will rebase once everything else gets squared away.

**Comment by harawata** [comment]
@hazendaz That would be great. Thank you!
Java version requirement can be a hard limit to some type of projects and I prefer treading carefully. I know it makes your work difficult and am sorry about that.
Please let me know if it gets too difficult for you. We can merge this and release the last Java 6 compatible version from a new branch later, I think.

**Comment by hazendaz** [comment]
No worries!  I know java versions are getting harder and harder to keep things straight.  This here was just really more follow-up after getting jdk9 building on things missed.  I had found that in some builds, not this one, that mybatis-parent upgrade to 30 would cause jdk9 to fail due to surefire.  I'm otherwise good for now.  Actually what I'd rather see is maven team get serious about underlying code usage.  In one case the team behind plexus re-introduced google collections 1.0 (guava now) on latest code release.  It's a bit silly in that area.  If they would fix all those issues, I think we would see next to nothing in this plugin as far as dependencies go.

**Comment by hazendaz** [comment]
Closing for time being and will reopen later.  There is some tricky business around maven 3.5.2+ which will break backwards compatibility with maven so I'll address that once this comes around again.

**Pull request closed without merging**
